"""Generate the close audit binder PDF from the signed close log.

Usage: binder.py close-log.jsonl reconciliation.json variance.json <period> out.pdf

One cover + one page per signed step: what ran, the key figures, the checks
that passed, who signed, when, and the sha256 of the signed result file —
so the binder proves the filed figures are the signed figures.
Requires reportlab.
"""
import json
import sys

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen.canvas import Canvas

MARGIN = 20 * mm
NAVY = (0.12, 0.16, 0.27)
GREY = (0.42, 0.45, 0.50)


class Page:
    def __init__(self, c: Canvas):
        self.c = c
        self.y = A4[1] - MARGIN

    def head(self, text, size=16):
        self.c.setFillColorRGB(*NAVY)
        self.c.setFont("Helvetica-Bold", size)
        self.c.drawString(MARGIN, self.y, text)
        self.y -= size + 8

    def line(self, text, size=10, indent=0, bold=False, grey=False):
        self.c.setFillColorRGB(*(GREY if grey else (0, 0, 0)))
        self.c.setFont("Helvetica-Bold" if bold else "Helvetica", size)
        self.c.drawString(MARGIN + indent, self.y, text[:110])
        self.y -= size + 4

    def gap(self, h=8):
        self.y -= h


STEP_TITLES = {"step1": "Step 1 — Bank reconciliation",
              "step2": "Step 2 — Variance report vs budget",
              "step3": "Step 3 — Management pack"}


def step_details(step: str, rec: dict, var: dict) -> list[str]:
    if step == "step1":
        rs = rec["reconciliation_statement"]
        out = [f"Balance per bank statement      £{rs['balance_per_bank_gbp']:,.2f}",
               f"Less unpresented payments       £{rs['less_unpresented_payments_gbp']:,.2f}",
               f"Add uncleared lodgements        £{rs['add_uncleared_lodgements_gbp']:,.2f}",
               f"Balance per cashbook            £{rs['cashbook_closing_balance_gbp']:,.2f}",
               f"Statement lines explained: {rec['matched']}/{rec['statement_lines']}",
               "Checks: C1 chain, C2 all lines explained, C3 rec identity to the penny, "
               "C4 cashbook integrity, C5 conservation"]
        for i in rec["closing_items"]:
            flag = "  [STALE]" if i["stale"] else ""
            out.append(f"  item: {i['description'][:60]}  £{i['amount_gbp']:,.2f}{flag}")
        return out
    if step == "step2":
        out = [f"Lines: {var['line_count']}; flagged at ±{var['flag_threshold_k']:,.0f}k: "
               f"{var['flagged_count']}; total variance {var['total_variance_k']:+,.1f}k (£'000)",
               "Checks: C1 lines, C2 every variance re-derived, C3 totals cross-foot, C4 flags"]
        out += [f"  FLAG {l['line'][:44]}  actual {l['mtd_actual_k']:,.0f}  bud "
                f"{l['mtd_budget_k']:,.0f}  var {l['variance_k']:+,.1f}"
                for l in var["lines"] if l["flagged"]]
        return out
    return ["Pack filled from signed step 1 + step 2 outputs only.",
            "Checks: C1 cash figures to the penny, C2 every variance row verbatim, C3 totals",
            "Commentary numbers outside signed sources were listed for reviewer verification."]


def main(log_path, rec_path, var_path, period, out_path):
    records = [json.loads(l) for l in open(log_path)]
    rec, var = json.load(open(rec_path)), json.load(open(var_path))

    c = Canvas(out_path, pagesize=A4)
    p = Page(c)
    p.gap(60)
    p.head("Caldergate Distribution Group Ltd", 20)
    p.head(f"Month-end close audit binder — {period}", 15)
    p.gap(6)
    p.line("Every AI-assisted step of this close: inputs, figures, checks, and the "
           "named reviewer who signed it.", grey=True)
    p.line("Generated by the close-pack skills. Fictitious data (demo estate).", grey=True)
    p.gap(14)
    for r in records:
        p.line(f"{STEP_TITLES.get(r['step'], r['step'])}  —  signed {r['signed_at_utc']} "
               f"by {r['reviewer']}", bold=True)
    c.showPage()

    for r in records:
        p = Page(c)
        p.head(STEP_TITLES.get(r["step"], r["step"]), 14)
        p.line(f"Signed: {r['signed_at_utc']}   Reviewer: {r['reviewer']}", bold=True)
        if r.get("note"):
            p.line(f"Reviewer decision: {r['note']}", size=9)
        p.line(f"Result file: {r['result_file'].split('/')[-1]}", size=8, grey=True)
        p.line(f"sha256: {r['result_sha256']}", size=8, grey=True)
        p.gap()
        for detail in step_details(r["step"], rec, var):
            p.line(detail, size=9, indent=4)
        p.gap(12)
        p.line("The sha256 above seals the signed result file; the filed figures are "
               "the signed figures.", size=8, grey=True)
        c.showPage()
    c.save()
    print(f"binder written: {out_path} ({len(records)} step page(s) + cover)")


if __name__ == "__main__":
    main(*sys.argv[1:6])
